---
# Setup service accounts
#
# We delegate this process to our domain controller since the required AD services are there for
# win_domain_user to interact with. 
- name: Ensure SQL Service account is present
  win_user:
    name: "{{ mssql_sqlsvc_account }}"
    # firstname: "{{ mssql_instance_name }}"
    # surname: SQLSvc
    password: "{{ mssql_sqlsvc_account_pass }}"
    password_never_expires: yes
    user_cannot_change_password: yes
    description: "SQL Service account for {{ inventory_hostname }}\\{{ mssql_instance_name }}"
    state: present
    # path: "{{ mssql_base_ldap_path }}"
    groups:
      - Users
  tags: service_account

- name: Ensure SQL Agent Service account is present
  win_user:
    name: "{{ mssql_agentsvc_account }}"
    # firstname: "{{ mssql_instance_name }}"
    # surname: AgentSvc
    password: "{{ mssql_agentsvc_account_pass }}"
    password_never_expires: yes
    user_cannot_change_password: yes
    description: "SQL Agent service account for {{ inventory_hostname }}\\{{ mssql_instance_name }}"
    state: present
    # path: "{{ mssql_base_ldap_path }}"
    groups: Users
  tags: service_account